### ISSUE TITLE
Article links on chunkypng.com 404

### ISSUE THREAD

**Issue by moonhouse** [wvanbergen/chunky_png#119]
The links to http://chunkypng.com/2014/11/07/the-value-of-a-pure-ruby-library.html, http://chunkypng.com/2010/01/17/ode-to-array-pack-and-string-unpack.html and http://chunkypng.com/2010/01/14/memory-efficiency-when-using-ruby.html leads to a 404 served by GitHub Pages. 

If I clone the repository and serve locally using `bundle exec jekyll serve` they work without problem (jekyll 3.3.0 under ruby 2.3.3p222) so I suspect it might be something strange on Github's part.

**Comment by slothbear** [comment]
I tried following the three links as posted. All loaded successfully. Perhaps GitHub fixed the underlying problem.

**Comment by wvanbergen** [comment]
Perfect, closing in that case
