### ISSUE TITLE
Release gem with support for iTXt chunks?

### ISSUE THREAD

**Issue by patrickjaberg** [wvanbergen/chunky_png#126]
Hey @wvanbergen, thanks for the great work here.  What are the chances of releasing a gem with support iTXt chunks?  I'm happy to do some of the legwork here if that'd help.

Thanks!

**Comment by wvanbergen** [comment]
Version 1.3.9 has been released.

**Comment by wvanbergen** [comment]
Version 1.3.9 shipped with a regression: `Datastream#metadata` would fail with `iTXt` chunks present. I applied a shitty fix here: https://github.com/wvanbergen/chunky_png/commit/181437973ebd8b4fef6f20d75e1ccb0780100693. It basically ignores iTXt chunks to populate the metadata hash.

#124 is arguably a nicer way to fix the issue, but has some outstanding questions. If anybody wants to take a look at it and get it over the finish line, that would be great.
