### ISSUE TITLE
undefined method `value' for #<ChunkyPNG::Chunk::InternationalText:0x000000038f46e0>

### ISSUE THREAD

**Issue by Aradesh** [wvanbergen/chunky_png#127]
Hi, we cathed an exception with new version 1.3.9 during compass build.

 Warning: NoMethodError on line ["146"] of /var/lib/gems/2.1.0/gems/chunky_png-1.3.9/lib/chunky_png/datastream.rb: undefined method `value' for #<ChunkyPNG::Chunk::InternationalText:0x000000038f46e0>
    Run with --trace to see the full backtrace Use --force to continue.

**Comment by wvanbergen** [comment]
I pushed version 1.3.10 that addresses this issue.
