### ISSUE TITLE
NoMethodError: undefined method `b' for "\x00":String

### ISSUE THREAD

**Issue by pauloodd** [wvanbergen/chunky_png#150]
'**de.saumya.mojo:gem-maven-plugin**' Maven plugin is getting the error 'NoMethodError: undefined method `b' for "\x00":String' on **chunky_png.rb** file. 

Line: 146 
```
  # Null-byte, with the encoding set correctly to ASCII-8BIT (binary) in Ruby 1.9.
  # @return [String] A binary string, consisting of one NULL-byte.
  # @private
  EXTRA_BYTE = "\0".b
```

https://github.com/wvanbergen/chunky_png/commit/84d187188ee360a2a971a0a60befae8974173402

**Comment by wvanbergen** [comment]
Ruby 1.9 is no longer supported, as it has been end-of-life for over 5 years. Please upgrade to a newer Ruby version, or pin chunky_png on a version that works for you.
