### ISSUE TITLE
Getting "can't modify frozen string (TypeError)"

### ISSUE THREAD

**Issue by gleisernicolas** [wvanbergen/chunky_png#151]
Since the last version (1.3.13) i'am getting this error with the gem "rqrcode"  that have chunky_png as a dependencie, in further investigation i saw that this error occours inside the `lib/chunky_png/canvas.rb` file in the `inspect` method, exactly at line 302.

**Comment by wvanbergen** [comment]
That's a bug, will work on a fix.

**Comment by wvanbergen** [comment]
Fixed in 1.3.14, including adding a spec. Thanks for reporting
