### ISSUE TITLE
Palette is not preserved

### ISSUE THREAD

**Issue by beoran** [wvanbergen/chunky_png#16]
When loading an indexed png file, and saving it again, the palette is not preserved correctly. Only colors used are preserved, and their order is also messed up. For pixel art, it's important to keep the palette intact and sorted as it was in the original image. That's why I think images loaded as indexed files png files should have their palette preserved in the original order with the original colors. 

Example of the problem:  
 image = ChunkyPNG::Image.from_file('tiles_1000_world.png')
  # get 'tiles_1000_world.png' from https://github.com/beoran/eruta/blob/master/data/image/tile/tiles_1000_world.png
 image.save("try2.png", :color_mode => ChunkyPNG::COLOR_INDEXED)
  # If you open the two files ,in say, GIMP, you'l see the second one has a mutilated palette compared to the first one.

Thanks, and kind regards, 

Beoran.

**Comment by wvanbergen** [comment]
Going to close this; fixing this would be a major rewrite of the library.
