### ISSUE TITLE
from_rgb_stream : calculation of width and height

### ISSUE THREAD

**Issue by TW-D** [wvanbergen/chunky_png#160]
Hello, 

I use 'from_rgb_stream' from 'ChunkyPNG::Canvas', how to calculate width and height automatically from 'rgb-stream' data? Because my tests corrupt the image.

Thanks for your help.

**Comment by wvanbergen** [comment]
After parsing the RGB stream, the resulting Canvas has `#width` and `#height` that you can call

**Comment by TW-D** [comment]
Thanks wvanberge but i wasn't specific enough. Here is the code :

```ruby
require('chunky_png')
include(ChunkyPNG)

# Constants

RGB_SIZE = 6

binary = File.open('./data', 'rb')
hexStream = ""
binary.each_char() do |char|
    hexStream += char.unpack('H*').join()
end
binary.close()

rgbStream = hexStream.scan(/.{#{RGB_SIZE}}/)

if (rgbStream.last().size() === RGB_SIZE)
    pp(ChunkyPNG::Canvas.methods())

    # how to calculate the width and height ?
    ChunkyPNG::Canvas.from_rgb_stream(74, 74, [rgbStream.join()].pack('H*')).save('./test.png')

end

image = Image.from_file('./test.png')
build = File.open('./test', 'wb')
build.write([image.to_rgb_stream().unpack('H*').join()].pack('H*'))
build.close()
```

**Comment by wvanbergen** [comment]
You can't calculate those an RGB strean is just a stream of pixels, so there's no way to know whether a stream of 4 pixels is a 1x4 image or a 2x2. This is why you have to supply these arguments.

**Comment by TW-D** [comment]
If we know the number of pixels in an image of 1x1 it can not help me ?

**Comment by wvanbergen** [comment]
`from_rgb_stream` basically is: "please construct a canvas of this size, and use this pixeldata for it."

If you know the image is 1x1, you can use `1, 1` as first two arguments to `from_rgb_stream`. The RGB stream for the third argument should then be 3 bytes long.

**Comment by TW-D** [comment]
Thank you very much, this is an elegant solution.
