### ISSUE TITLE
Requires sorted_set gem with Ruby 3.0

### ISSUE THREAD

**Issue by dleidert** [wvanbergen/chunky_png#163]
I think this gem requires the `sorted_set` gem when used with Ruby 3.0 which split out `SortedSet` and does no longer distribute it with the standard library.

**Comment by wvanbergen** [comment]
This is fixed already in the latest version (1.4.0)

**Comment by dleidert** [comment]
This might be a totally dumb question, but: where did you fix this? The [diff](https://github.com/wvanbergen/chunky_png/compare/v1.3.15...master) doesn't show anything that seems related. I'd have thought that you need to add the gem dependency to your gemspec file for Ruby >= 3.

**Comment by wvanbergen** [comment]
https://github.com/wvanbergen/chunky_png/pull/154
