### ISSUE TITLE
undefined method

### ISSUE THREAD

**Issue by ctadeu** [wvanbergen/chunky_png#81]
Hello

I'm gettin gthis error when try to use the gem

/var/lib/gems/1.9.1/gems/chunky_png-1.3.3/lib/chunky_png/canvas/drawing.rb:97:in `line_xiaolin_wu': undefined method `-' for nil:NilClass (NoMethodError)
        from /var/lib/gems/1.9.1/gems/chunky_png-1.3.3/lib/chunky_png/canvas/drawing.rb:235:in `rect'
        from sample.rb:22:in `<main>'

**Comment by ctadeu** [comment]
doing that:
images = [
  ChunkyPNG::Image.from_file('baseline.png'),
  ChunkyPNG::Image.from_file('screenshot.png')
]
 
diff = []
 
images.first.height.times do |y|
  images.first.row(y).each_with_index do |pixel, x|
    diff << [x,y] unless pixel == images.last[x,y]
  end
end

x, y = diff.map{ |xy| xy[0] }, diff.map{ |xy| xy[1] }
 
images.last.rect(x.min, y.min, x.max, y.max, ChunkyPNG::Color.rgb(0,255,0))
images.last.save('diff.png')

**Comment by wvanbergen** [comment]
What are the values `x.min, y.min, x.max, y.max` before you call `rect`?

**Comment by ctadeu** [comment]
yes, you right!
