### ISSUE TITLE
About comparison two large size png 

### ISSUE THREAD

**Issue by RakutenStone** [wvanbergen/chunky_png#84]
I use iPad to take a screenshot and save as png image.
Its size is about 1.3M.
When I run the code below:
images.first.height.times do |y|
  images.first.row(y).each_with_index do |pixel, x|
    diff << [x,y] unless pixel == images.last[x,y]
  end
end

There will be an error "out of bound " or sth.
Sorry I cannot remember the detail error message.
How can I solve this issue.

**Comment by wvanbergen** [comment]
Can you run this again, and paste the error message plus the stack trace here?

**Comment by RakutenStone** [comment]
I ran it again and paste the error message here:

/Library/Ruby/Gems/2.0.0/gems/chunky_png-1.3.4/lib/chunky_png/canvas.rb:334:in `assert_xy!': Coordinates (768,0) out of bounds! (ChunkyPNG::OutOfBounds)
	from /Library/Ruby/Gems/2.0.0/gems/chunky_png-1.3.4/lib/chunky_png/canvas.rb:174:in `[]'
	from diff.rb:49:in `block (2 levels) in <main>'
	from diff.rb:48:in `each'
	from diff.rb:48:in `each_with_index'
	from diff.rb:48:in `block in <main>'
	from diff.rb:47:in `times'
	from diff.rb:47:in `<main>'

**Comment by wvanbergen** [comment]
Most likely, the two images you're using do not have the same dimensions. So the `x` coordinate you get from the first image is too high for the last image. Mind sharing the two images?

**Comment by RakutenStone** [comment]
Thank you for your help.
You are right the dimensions are not same.
I think QA team take the screenshot by different ipads.
I think it can be closed now.
