### ISSUE TITLE
Feature request:  Negative colours

### ISSUE THREAD

**Issue by istrasci** [wvanbergen/chunky_png#93]
It would be nice to have some way to calculate the negative of a given colour.

**Comment by wvanbergen** [comment]
What is the use case for this? And how is "negative" defined? `255 - value` for R,G, and B?

**Comment by wvanbergen** [comment]
Going to close this - it's my policy to close feature request issues, especially without clear use case and/or specification.

I'd be willing to consider a pull requests that implements this, but I am not going to work on this myself.
