### ISSUE TITLE
[DEPRECATION] requiring "RMagick" is deprecated. Use "rmagick" instead

### ISSUE THREAD

**Issue by DarkElement2** [wvanbergen/chunky_png#99]
Warning:[rake --prereqs] /usr/local/rvm/gems/ruby-2.2.3/gems/activesupport-4.1.1/lib/active_support/values/time_zone.rb:285: warning: circular argument reference - now [DEPRECATION] requiring "RMagick" is deprecated. Use "rmagick" instead

Using Ruby 2.2.3
Rails: 4.1.1

**Comment by wvanbergen** [comment]
Fixed by #100
